
<?xml version="1.0" encoding="ISO-8859-1" ?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:tns= "http://localhost/Sistemas-Web-master/php/VerifyPassWS.php?wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace= "http://localhost/Sistemas-Web-master/php/VerifyPassWS.php?wsdl">

<types>
	<xsd:schema targetNamespace="http://localhost/Sistemas-Web-master/php/VerifyPassWS.php?wsdl">
	<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
	<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" /> </xsd:schema>
</types>
<message name="sumarRequest">
	<part name="x" type="xsd:string" />
	<part name="y" type="xsd:string" />
</message>
<message name="sumarResponse">
	<part name="z" type="xsd:string" />
</message>
<portType name="validarPortType">
	<operation name="validar">
		<input message="tns:validarRequest" />
		<output message="tns:validarResponse" />
	</operation>
</portType>
<service name="validar">
	<soap:address location="http://localhost/Sistemas-Web-master/php/VerifyPassWS.php" />
</service>
</definitions>